theme: jekyll-theme-cayman
title: Kids' Corners Everywhere
description: A list of curated resources to help event/conference organisers around the world with setting up kids' corners on their events.
